apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cherry
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: stack-values
    files:
       - stack-values=./stack-values.yaml
